# Generated by Django 3.2.16 on 2022-10-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='hello', upload_to=''),
            preserve_default=False,
        ),
    ]
